### PR TITLE
Construct Node builder with entropy seed

### PR DESCRIPTION
**Pull request by jurvis**
Not sure if this is a good idea, but would be really nice to construct a `Builder` and bring-your-own entropy

### CODE REVIEW

**Comment by tnull** [comment]
Thanks for looking into this! I think we don't want to introduce yet another `Entropy` struct, as this is unfortunately redundant to `WalletEntropySource`. It's basically all there already, just not exposed yet in the bindings. While exposing an alternative constructor might make sense if we have no other option, I'd like to explore once more if there is a way to maintain the builder pattern in bindings, i.e., allow for `Builder::set_entropy_seed_bytes` to be exposed in a usable way.

**Comment by jurvis** [comment]
@tnull 
> I'd like to explore once more if there is a way to maintain the builder pattern in bindings, i.e., allow for Builder::set_entropy_seed_bytes to be exposed in a usable way.

That was an idea I had secondary to this one, I’m willing to take a stab at it and see if I can come up with something :)

**Comment by jurvis** [comment]
@tnull the immediate issue that comes to mind is that `Builder::set_entropy_seed_bytes` expects an array `[u8; 64]`, and I don't think that is currently something we can expose directly to bindings without changing the method signature to expect `Vec<u8>` instead. thoughts?

**Comment by tnull** [comment]
Well, even before that the issue is that the builder pattern requires to return `&mut`, which doesn't immediately work in bindings. If we got a good work around for this, I'm sure we'll come up with a good solution for the array issue.

**Comment by tnull** [comment]
Closing this for now, please reopen the PR upstream once we figured out a way forward to make the builder pattern work in bindings!

**Pull request closed without merging**
